name: SHRP CI
on:
  workflow_dispatch:
    inputs:
      telegram:
        description: 'Set this to true if you want send to telegram'
        required: true

env:
  # Recovery Manifest URL with -b branch
  MANIFEST: "git://github.com/SHRP/platform_manifest_twrp_omni.git -b v3_9.0"
  
  # Your Device Tree Link
  DT_LINK: "https://github.com/SHRP-Devices/device_samsung_j4lte"
  
  # Your Device's Vendor name as in used inside DT. Example: xiaomi, samsung, asus, etc.
  VENDOR: "samsung"
  
  # Your Device's Codename as in used inside DT." Example: nikel, phoenix, ginkgo, etc.
  CODENAME: "j4lte"
  
  # Kernel repo link with optional -b branch. Only for building kernel from source. Ignore if using prebuilt.
  KERNEL_LINK: "https://github.com/YariKartoshe4ka/android_kernel_samsung_j4lte -b master"
  
  # Set as recoveryimage (or bootimage if no recovery partition avaiable)
  TARGET: "recoveryimage"
  
  # eng by default, change the variable if you want userdebug
  FLAVOR: "eng"
 
  # For qualcomm devices put git clone https://github.com/omnirom/android_vendor_qcom_opensource_commonsys --depth=1 -b android-9.0 vendor/qcom/opensource/commonsys in EXTRA CMD
  # If you want to Execute any external Command Before Compilation Starts
  EXTRA_CMD: ""
  
  TZ: "Europe/Moscow"

jobs:
  SHRP-CI:
    runs-on: ubuntu-20.04

    steps:
      - name: Clean Up Runner
        uses: rokibhasansagar/slimhub_actions@main

      - name: Compile Recovery
        uses: ElytrA8/Recovery-Compiler@production

      - name: Get path to ZIP
        run: echo "::set-output name=PATH_TO_ZIP::$(echo ${BuildPath}/out/target/product/${CODENAME}/*stable*.zip)"
        id: path

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: SHRP Recovery
          path: ${{ steps.path.outputs.PATH_TO_ZIP }}

      - name: Send To Telegram
        if: ${{ github.event.inputs.telegram }} == 'true'
        run: |
          curl "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendDocument" \
               --form-string "chat_id=${{ secrets.TELEGRAM_TO }}" \
               --form-string "disable_web_page_preview=true" \
               --form-string "parse_mode=html" \
               --form-string "caption=<i> SHRP Recovery </i> for <b> '$VENDOR' '$CODENAME' </b> | Build finished on <b> $(date) </b>" \
               -F document=@"${{ steps.path.outputs.PATH_TO_ZIP }}"
